### ISSUE TITLE
Delta Configuration Not Matching Current Marlin 2.0.x[Bug]

### ISSUE THREAD

**Issue by Firworksyt** [cp2004/OctoPrint-EEPROM-Marlin#26]
#### Describe the bug
The Delta settings page in the plugin does not match the response from the M665 Gcode command on the current version of Marlin.

#### Steps To Reproduce

On printer running Marlin 2.0.7.2
1. Issue M503 in terminal
2. Note format of M665
3. Go to Delta Settings in plugin
4. Note incorrect calibration radius which contains the value of A rod trim.

#### Expected behavior
Delta settings screen in plugin matches definition of M665 command and supports view/edit/backup/restore of diagonal rod length adjustments.

#### Logs

`octoprint.log`:
2021-01-05 04:19:21,676 - octoprint.startup - INFO - ******************************************************************************
2021-01-05 04:19:21,677 - octoprint.startup - INFO - Starting OctoPrint 1.5.2
2021-01-05 04:19:21,678 - octoprint.startup - INFO - ******************************************************************************
2021-01-05 04:19:22,090 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2021-01-05 04:19:22,148 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2021-01-05 04:19:22,148 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 8.8.8.8:53 is working
2021-01-05 04:19:22,149 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2021-01-05 04:19:22,564 - octoprint.startup - INFO - Blacklist processing done, adding 12 blacklisted plugin versions: roomtemp (any), GcodeEditor (0.1.1), GcodeEditor (0.2.0), GcodeEditor (0.2.1), GcodeEditor (0.2.2), GcodeEditor (0.2.3), GcodeEditor (0.2.4), GcodeEditor (0.2.5), GcodeEditor (0.2.6), GcodeEditor (0.2.8), gcodeleveling (0.1.0), gcodeleveling (0.1.1)
2021-01-05 04:19:22,584 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2021-01-05 04:19:23,402 - octoprint.plugin.core - INFO - Plugin Marlin Flasher (0.1.4) is disabled.
2021-01-05 04:19:23,553 - octoprint.plugin.core - INFO - Plugin Octolapse (0.3.4) is disabled.
2021-01-05 04:19:23,634 - octoprint.plugin.core - INFO - Plugin Delta-Micro-Calibrator (1.0.4) is disabled.
2021-01-05 04:19:23,818 - octoprint.startup - INFO - Added settings overlay from plugin dashboard
2021-01-05 04:19:23,827 - octoprint.plugin.core - INFO - Found 30 plugin(s) providing 27 mixin implementations, 60 hook handlers
2021-01-05 04:19:23,919 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2021-01-05 04:19:23,934 - octoprint.server - INFO - Intermediary server started
2021-01-05 04:19:23,951 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2021-01-05 04:19:24,540 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2021-01-05 04:19:24,543 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: u"Need(method='role', value=u'plugin_action_command_notification_show')")
2021-01-05 04:19:24,544 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: u"Need(method='role', value=u'plugin_action_command_notification_clear')")
2021-01-05 04:19:24,545 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: u"Need(method='role', value=u'plugin_action_command_prompt_interact')")
2021-01-05 04:19:24,546 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: u"Need(method='role', value=u'plugin_announcements_read')")
2021-01-05 04:19:24,547 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: u"Need(method='role', value=u'plugin_announcements_manage'), Need(method='role', value=u'plugin_announcements_read')")
2021-01-05 04:19:24,548 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: u"Need(method='role', value=u'plugin_appkeys_admin')")
2021-01-05 04:19:24,549 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: u"Need(method='role', value=u'plugin_backup_access')")
2021-01-05 04:19:24,549 - octoprint.server - INFO - Added new permission from plugin dashboard: PLUGIN_DASHBOARD_ADMIN (needs: u"Need(method='role', value=u'plugin_dashboard_admin')")
2021-01-05 04:19:24,550 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: u"Need(method='role', value=u'plugin_firmware_check_display')")
2021-01-05 04:19:24,552 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: u"Need(method='role', value=u'plugin_logging_manage')")
2021-01-05 04:19:24,552 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: u"Need(method='role', value=u'plugin_pi_support_check')")
2021-01-05 04:19:24,553 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: u"Need(method='role', value=u'plugin_pluginmanager_manage')")
2021-01-05 04:19:24,554 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: u"Need(method='role', value=u'plugin_pluginmanager_install'), Need(method='role', value=u'plugin_pluginmanager_manage')")
2021-01-05 04:19:24,555 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: u"Need(method='role', value=u'plugin_softwareupdate_check')")
2021-01-05 04:19:24,556 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: u"Need(method='role', value=u'plugin_softwareupdate_update')")
2021-01-05 04:19:24,557 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: u"Need(method='role', value=u'plugin_softwareupdate_configure')")
2021-01-05 04:19:24,801 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2021-01-05 04:19:24,838 - octoprint.plugins.excluderegion - INFO - Logging mode set to 'octoprint'
2021-01-05 04:19:24,840 - octoprint.plugins.excluderegion - INFO - Setting update detected: g90InfluencesExtruder=False, clearRegionsAfterPrintFinishes=False, mayShrinkRegionsWhilePrinting=False, loggingMode=octoprint, enteringExcludedRegionGcode=None, exitingExcludedRegionGcode=None, extendedExcludeGcodes={'M73': {"gcode": "M73", "type": "ExcludedGcode", "mode": "merge", "description": "Suppress progress updates while excluding and output the most recent progress values encountered when exiting the excluded area"}, 'M117': {"gcode": "M117", "type": "ExcludedGcode", "mode": "last", "description": "Suppress display messages while excluding and output the last message encountered when exiting the excluded area"}, 'G4': {"gcode": "G4", "type": "ExcludedGcode", "mode": "exclude", "description": "Ignore all dwell commands in an excluded area to reduce delays while excluding"}, 'M205': {"gcode": "M205", "type": "ExcludedGcode", "mode": "merge", "description": "Record advanced setting changes while excluding and apply the most recent values in a single command after exiting the excluded area"}, 'M204': {"gcode": "M204", "type": "ExcludedGcode", "mode": "merge", "description": "Record default acceleration changes while excluding and apply the most recent values in a single command after exiting the excluded area"}}, atCommandActions={'ExcludeRegion': [{"action": "enable_exclusion", "type": "AtCommandAction", "command": "ExcludeRegion", "parameterPattern": "^\\s*(enable|on)(\\s|$)", "description": "Default action to enable exclusion"}, {"action": "disable_exclusion", "type": "AtCommandAction", "command": "ExcludeRegion", "parameterPattern": "^\\s*(disable|off)(\\s|$)", "description": "Default action to disable exclusion"}]}
2021-01-05 04:19:24,865 - octoprint.plugins.eeprom_marlin - INFO - EEPROM Data initialised
2021-01-05 04:19:24,867 - octoprint.plugins.eeprom_marlin - INFO - Backup metadata initialised
2021-01-05 04:19:24,868 - octoprint.plugins.eeprom_marlin - INFO - All EEPROM editor modules loaded
2021-01-05 04:19:25,668 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2021-01-05 04:19:26,471 - octoprint.util.pip - INFO - Version of pip is 19.1.1
2021-01-05 04:19:26,473 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-01-05 04:19:26,473 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-01-05 04:19:26,485 - octoprint.plugin.core - INFO - Initialized 27 plugin implementation(s)
2021-01-05 04:19:26,507 - octoprint.plugin.core - INFO - 30 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Bed Visualizer (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_bedlevelvisualizer
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Dashboard (1.16.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_dashboard
| !Delta-Micro-Calibrator (1.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DuCalibrator
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  DisplayLayerProgress Plugin (1.24.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_DisplayLayerProgress
|  Error Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  Exclude Region (0.3.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_excluderegion
|  File Check (2020.8.7) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_file_check
|  Firmware Check (2020.9.23) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmware_check
|  Firmware Updater (1.7.6) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmwareupdater
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/gcodeviewer
|  InfluxDB Plugin (1.3.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_influxdb
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Marlin EEPROM Editor (3.0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
| !Marlin Flasher (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_marlin_flasher
| !Octolapse (0.3.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  PortLister (0.1.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_portlister
|  Preheat Button (0.5.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_preheat
|  Resource Monitor (0.2.7) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_resource_monitor
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2021-01-05 04:19:26,538 - octoprint.environment - INFO - Detected environment is Python 2.7.16 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 1500.0
|      ram: 4041732096
|  os:
|      bits: 32
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 4 Model B Rev 1.1
|          octopi_version: 0.17.0
|          throttle_state: '0x0'
|  python:
|      pip: 19.1.1
|      version: 2.7.16
|      virtualenv: /home/pi/oprint
2021-01-05 04:19:26,554 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2021-01-05 04:19:26,578 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2021-01-05 04:19:27,238 - octoprint.server - INFO - Shutting down intermediary server...
2021-01-05 04:19:27,509 - octoprint.server - INFO - Intermediary server shut down
2021-01-05 04:19:27,512 - octoprint.events - INFO - Processing startup event, this is our first event
2021-01-05 04:19:27,512 - octoprint.events - INFO - Adding 2 events to queue that were held back before startup event
2021-01-05 04:19:27,517 - octoprint.plugins.influxdb - INFO - connecting: database='octoprint', host='192.168.1.77', ssl=False, use_udp=False
2021-01-05 04:19:27,518 - octoprint.server - INFO - Autoconnect on startup is configured, trying to connect to the printer...
2021-01-05 04:19:27,518 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2021-01-05 04:19:27,567 - octoprint.plugins.influxdb - INFO - Using existing database `octoprint`
2021-01-05 04:19:27,613 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2021-01-05 04:19:27,641 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-01-05 04:19:27,644 - octoprint.plugins.influxdb - ERROR - Disconnected from InfluxDB. Attempting to reconnect.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_influxdb/__init__.py", line 212, in influx_emit
    self.influx_db.write_points([point], retention_policy=self.influx_retention_policy)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/influxdb/client.py", line 608, in write_points
    consistency=consistency)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/influxdb/client.py", line 685, in _write_points
    protocol=protocol
  File "/home/pi/oprint/local/lib/python2.7/site-packages/influxdb/client.py", line 419, in write
    headers=headers
  File "/home/pi/oprint/local/lib/python2.7/site-packages/influxdb/client.py", line 378, in request
    raise InfluxDBClientError(err_msg, response.status_code)
InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"new\" on measurement \"events\" is type boolean, already exists as type float dropped=1"}
2021-01-05 04:19:27,685 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2021-01-05 04:19:28,766 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2021-01-05 04:19:28,781 - octoprint.server - INFO - Trying to connect to configured serial port None
2021-01-05 04:19:28,840 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2021-01-05 04:19:28,846 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2021-01-05 04:19:28,847 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2021-01-05 04:19:28,858 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 7 port/baudrate candidates: /dev/ttyACM0@115200, /dev/ttyACM0@250000, /dev/ttyACM0@230400, /dev/ttyACM0@57600, /dev/ttyACM0@38400, /dev/ttyACM0@19200, /dev/ttyACM0@9600
2021-01-05 04:19:28,865 - octoprint.util.comm - INFO - Serial detection: Trying port /dev/ttyACM0, baudrate 115200
2021-01-05 04:19:28,867 - octoprint.util.comm - INFO - Connecting to port /dev/ttyACM0, baudrate 115200
2021-01-05 04:19:28,874 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2021-01-05 04:19:28,878 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-05 04:19:28,882 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Operational"
2021-01-05 04:19:28,887 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-01-05 04:19:28,894 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2021-01-05 04:19:28,895 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2021-01-05 04:19:28,914 - octoprint.plugins.tracking - INFO - Sent tracking event system_unthrottled, payload: {u'throttled_mask': 0, u'throttled_voltage_now': False, u'throttled_voltage_past': False, u'throttled_overheat_now': False, u'throttled_now': False, u'throttled_past': False, u'throttled_overheat_past': False}
2021-01-05 04:19:28,924 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 2.0.7.2 (Jan  3 2021"
2021-01-05 04:19:28,944 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2021-01-05 04:19:28,992 - octoprint.plugins.eeprom_marlin - INFO - M503 detected, collecting data
2021-01-05 04:19:28,995 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:19:28,997 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M149 C ; Units in Celsius

2021-01-05 04:19:29,018 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:19:29,019 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M906 X900 Y900 Z900

2021-01-05 04:19:29,020 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:19:29,021 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M906 T0 E1000

2021-01-05 04:19:29,024 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:19:29,024 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M569 S1 X Y Z

2021-01-05 04:19:29,026 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:19:29,027 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M569 S1 T0 E

2021-01-05 04:19:29,029 - octoprint.plugins.eeprom_marlin - INFO - Finished data collection, updating UI
2021-01-05 04:19:29,323 - octoprint.plugins.tracking - INFO - Sent tracking event printer_connected, payload: {u'printer_baudrate': 0, u'printer_port': None, u'firmware_name': u'Marlin 2.0.7.2 (Jan  3 2021'}
2021-01-05 04:19:29,669 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._http._tcp.local.' for _http._tcp.local.
2021-01-05 04:19:30,486 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._octoprint._tcp.local.' for _octoprint._tcp.local.
2021-01-05 04:19:30,498 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2021-01-05 04:19:30,562 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2021-01-05 04:19:30,720 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-01-05 04:19:30,723 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.23
2021-01-05 04:19:31,326 - octoprint.server.util.flask - INFO - Passively logging in user firworks from ::ffff:192.168.1.23
2021-01-05 04:19:31,327 - octoprint.access.users - INFO - Logged in user: firworks
2021-01-05 04:19:31,760 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2021-01-05 04:19:31,801 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-01-05 04:19:31,888 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-01-05 04:19:31,989 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 22.1GB. That is considered sufficient for updating.
2021-01-05 04:19:31,990 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2021-01-05 04:19:32,257 - octoprint.plugins.bedlevelvisualizer - INFO - OctoPrint-BedLevelVisualizer loaded!
2021-01-05 04:19:32,260 - octoprint.plugins.dashboard - INFO - Dashboard started
2021-01-05 04:19:32,271 - octoprint.plugins.influxdb - INFO - connecting: database='octoprint', host='192.168.1.77', ssl=False, use_udp=False
2021-01-05 04:19:32,424 - octoprint.plugins.influxdb - INFO - Using existing database `octoprint`
2021-01-05 04:19:32,458 - octoprint.plugins.portlister - INFO - Port Lister () {}
2021-01-05 04:19:32,664 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.8/'}
2021-01-05 04:19:32,702 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 9}
2021-01-05 04:19:33,136 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {u'python': '2.7.16', u'os': u'linux', u'ram': 4041732096L, u'octopi_version': u'0.17.0', u'version': u'1.5.2', u'pip': '19.1.1', u'cores': 4, u'freq': 1500.0, u'pi_model': u'Raspberry Pi 4 Model B Rev 1.1', u'bits': 32}
2021-01-05 04:19:33,608 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {u'python': '2.7.16', u'os': u'linux', u'ram': 4041732096L, u'octopi_version': u'0.17.0', u'version': u'1.5.2', u'plugins': u'displaylayerprogress:1.24.0,firmwareupdater:1.7.6,resource_monitor:0.2.7,portlister:0.1.10,influxdb:1.3.2,bedlevelvisualizer:1.0.0,excluderegion:0.3.0,dashboard:1.16.3,eeprom_marlin:3.0.1,preheat:0.5.1', u'pip': '19.1.1', u'cores': 4, u'freq': 1500.0, u'pi_model': u'Raspberry Pi 4 Model B Rev 1.1', u'bits': 32}
2021-01-05 04:19:33,836 - octoprint.server.util.sockjs - INFO - User firworks logged in on the socket from client ::ffff:192.168.1.23
2021-01-05 04:19:43,484 - octoprint.server.preemptive_cache - INFO - ... done in 10.82s
2021-01-05 04:19:43,485 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.3/'}
2021-01-05 04:19:44,073 - octoprint.server.preemptive_cache - INFO - ... done in 0.59s
2021-01-05 04:19:53,136 - octoprint.server.util.flask - INFO - Passively logging in user firworks from ::ffff:192.168.1.23
2021-01-05 04:19:53,138 - octoprint.access.users - INFO - Logged in user: firworks
2021-01-05 04:19:53,240 - octoprint.server.util.sockjs - INFO - Client connection closed: ::ffff:192.168.1.23
2021-01-05 04:19:54,009 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.23
2021-01-05 04:19:54,065 - octoprint.server.util.flask - INFO - Passively logging in user firworks from ::ffff:192.168.1.23
2021-01-05 04:19:54,066 - octoprint.access.users - INFO - Logged in user: firworks
2021-01-05 04:19:56,242 - octoprint.server.util.sockjs - INFO - User firworks logged in on the socket from client ::ffff:192.168.1.23
2021-01-05 04:20:06,470 - octoprint.plugins.eeprom_marlin - INFO - M503 detected, collecting data
2021-01-05 04:20:06,500 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:20:06,502 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M149 C ; Units in Celsius

2021-01-05 04:20:06,547 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:20:06,548 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M906 X900 Y900 Z900

2021-01-05 04:20:06,552 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:20:06,554 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M906 T0 E1000

2021-01-05 04:20:06,559 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:20:06,559 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M569 S1 X Y Z

2021-01-05 04:20:06,561 - octoprint.plugins.eeprom_marlin - WARNING - Did not recognise EEPROM data, skipping line
2021-01-05 04:20:06,562 - octoprint.plugins.eeprom_marlin - WARNING - Line: echo:  M569 S1 T0 E

2021-01-05 04:20:06,570 - octoprint.plugins.eeprom_marlin - INFO - Finished data collection, updating UI

#### Versions, system information

**Plugin** Version: 3.0.1

**OctoPrint**

Version: 1.5.2

Operating System running OctoPrint: Raspbian 10 (Buster)

**Printer** model & firmware version: Anycubic Kossel Linear Plus with SKR V1.3 running Marlin 2.0.7.2

**Browser:** Chrome

**Additional context, screenshots, anything else you think might be useful**

Gcode Example from my machine:

Send: M503
Recv: echo:; Delta settings: L<diagonal rod> R<radius> H<height> S<segments per sec> XYZ<tower angle trim> ABC<rod trim>
Recv: echo:  M665 L267.0000 R133.5951 H270.6000 S80.0000 X0.2631 Y-0.0122 Z-0.2509 A0.0000 B0.0000 C0.0000

I've edited the current plugin already to successfully support this but I cannot figure out how to actually setup a proper development environment as per the contribution guidelines to make a commit and pull request for this issue. The above log and behavior report however is with a clean fresh install of the plugin.

**Comment by cp2004** [comment]
So I'm reading the documentation for marlin (https://marlinfw.org/docs/gcode/M665.html) about this code, and it lists the B parameter as the calibration radius. As far as I can tell, the plugin should be using this B parameter in this field. Could you explain a little more about which parameter you expected to be under 'Calibration radius' label? 

I don't have a delta machine, so have to go from the docs to create the plugin, or by someone else telling me otherwise. Might be able to read the source of the command, or ask in the Marlin discord to see if they know more info about the docs being different.

**Comment by Firworksyt** [comment]
I'll see if I can find the thread on the Marlin Github but they've mentioned that documentation is out of date and haven't gotten around to updating it still.

**Comment by cp2004** [comment]
@Firworksyt You mentioned you adjusted the plugin to work for you, if you can upload the files here I would be able to add them (with you as the co-author). I'll also ask on the Marlin discord at some point, unless maybe reading the source would be easier 😄.

**Comment by Firworksyt** [comment]
Sure, I'll clean it up some and test it out a bit more and then attach it here. I made the initial edit to see if I could figure it out and then came here when it worked.

I looked at the current Marlin source and here's where they're declaring the data structure to store delta configurations:

https://github.com/MarlinFirmware/Marlin/blob/f74015b4e57677cd033e116dab2331478edbe2ec/Marlin/src/module/settings.cpp#L266-L282

Here's where they're parsing a received M665 message:

https://github.com/MarlinFirmware/Marlin/blob/f74015b4e57677cd033e116dab2331478edbe2ec/Marlin/src/gcode/calibrate/M665.cpp#L30-L59

Here's where they're sending out a M665 as part of the settings report in response to something like an M503:

https://github.com/MarlinFirmware/Marlin/blob/f74015b4e57677cd033e116dab2331478edbe2ec/Marlin/src/module/settings.cpp#L3207-L3230

All of them show this format with ABC for rod length so I think the documentation is just wrong.

One question I had while looking at these though is how you want to handle SCARA printers. I know they're even less common than Deltas but it looks like Marlin has overlaid the M665 message to either be a Delta config or SCARA config. If someone with a SCARA printer tries the plugin it'll probably behave very strangely. The start of the M665 response does say either "SCARA settings:" or "Delta settings:" so you could probably key off of that.

**Comment by cp2004** [comment]
Yeah, SCARA is not handled at all. Could probably be done, with a flag in it's data entry. That's not actually something I decided on, since I adopted this plugin back in October. Of course, with V3 I re-wrote most of it but the concept of what commands etc. was still there from the old version. Now I've got it into a decent framework, we can think about things like this. Interestingly, in the 5 years this plugin has been around, no one has mentioned SCARA support in a single issue, out of [over 5K tracked installs](https://cp2004.github.io/OctoPluginStats). I'll see, if it is simple enough to set a flag (based on the response you mention) to change things, otherwise it is very low priority.

Thanks for the links, saves me some time clicking and trying to comprehend the Marlin structure for a while 🙂.

**Comment by cp2004** [comment]
Alright, I think I got this one. I'll let you know when there's a pre-release available to test, since I don't have a delta I hope I've read all the sources you posted correctly.

**Comment by cp2004** [comment]
There's a release candidate available for you to test this now: [3.1.0rc1](https://github.com/cp2004/OctoPrint-EEPROM-Marlin/releases/tag/3.1.0rc1). Feedback ticket #45 for any comments on the release. Stable release approx. 1 week depending on how the testing goes.
